### ISSUE TITLE
next collateral ratio

### ISSUE THREAD

**Issue by adrian-schnell** [defichain-api/dobby#126]
API output for vaults has the new attribute `nextCollateralRatio`. 

if the calculation is invalid (e.g. vault in liquidation), this value is `-1` or in some rare cases `null`.

**add this attribute for the vault cards**

**Comment by DerFuchs** [comment]
Implemented. Showing as new Card above vaults and used in vault card, too.
![image](https://user-images.githubusercontent.com/9048957/150754980-49d67c04-6379-41c6-abe1-c64bb988e945.png)
