### ISSUE TITLE
Return id of newly generated entries

### ISSUE THREAD

**Issue by DerFuchs** [defichain-api/dobby#47]
## summary
POST requests should always deliver the whole public information of the newly generated or altered database entries.

## affected
When perfoming

- POST /user/gateway
- POST /user/notification
- PUT /user/gateway
- PUT /user/notification
- [maybe even more]

## details
Maybe the result object of `POST /user/gateway` which looks like this:
```
{
    "state": "ok",
    "message": "notification gateway is created"
}
```
can be extended like this:
```
{
    "state": "ok",
    "message": "notification gateway is created"
    "data": {
            "gatewayId": 4,
            "type": "telegram",
            "value": "BuzzJoe"
        }
}
```

**Comment by adrian-schnell** [comment]
create gateway endpoint:

```
{
    "state": "ok",
    "message": "notification gateway is created",
    "data": {
        "gatewayId": 7,
        "type": "webhook",
        "value": "https://test.de"
    }
}
```

**Comment by adrian-schnell** [comment]
implementiert
