### ISSUE TITLE
test notification gateway (setup)

### ISSUE THREAD

**Issue by adrian-schnell** [defichain-api/dobby#59]
after creating a gateway, offer a btn  "test gateway" to check if it works

- api endpoint
- btn in GUI to trigger it

POST /gateways/test
Payload:
```
{
    "type":"webhook" // or telegram, mail
}
```

**Comment by adrian-schnell** [comment]
MAIL
<img width="642" alt="Bildschirmfoto 2021-12-06 um 00 37 56" src="https://user-images.githubusercontent.com/322735/144768859-8bf79c25-d1c5-4e51-9421-8eeff47b6a58.png">

**Comment by adrian-schnell** [comment]
Telegram
<img width="440" alt="Bildschirmfoto 2021-12-06 um 00 42 23" src="https://user-images.githubusercontent.com/322735/144768869-6d6e03db-ce64-4125-981c-c16070d761f9.png">

**Comment by adrian-schnell** [comment]
webhook 
![Bildschirmfoto 2021-12-06 um 00 41 59](https://user-images.githubusercontent.com/322735/144768884-63d29256-d6ae-4892-9867-4db6f360b65d.png)

**Comment by DerFuchs** [comment]
Available for Telegram, Mail will follow when mail gateway has been implemented
