### ISSUE TITLE
Make daily summary optional

### ISSUE THREAD

**Issue by DerFuchs** [defichain-api/dobby#86]
Some users don't want to receive daily summaries

**Comment by DerFuchs** [comment]
Agree. I can provide a suitable UI component in "Manage Notifications" in the Web UI.

**Comment by adrian-schnell** [comment]
added the new attribute "summaryInterval" to the PUT /user/settings endpoint with the possible values:

'none', 'daily', 'daily_2x', 'daily_3x', 'hourly'

**Comment by adrian-schnell** [comment]
possible payload:

```
{
    "theme": "dark",
    "language": "en",
    "summaryInterval": "hourly"
}
```
