### ISSUE TITLE
Consistent spelling of Dobby

### ISSUE THREAD

**Issue by Ulle84** [defichain-api/dobby#87]
### Motivation
Currently there are at least 3 different spellings of Dobby
* Dobby
* DOBBY
* D.O.B.B.Y.
[Consistency is key](https://themindfool.com/consistency-is-key/), so all spellings should be the same.

### Acceptance Criteria
* Consistent naming of Dobby is done

### Definition of Done
* Acceptance criteria met
* Tested
* Reviewed
* Merged

**Comment by adrian-schnell** [comment]
Spelling should be `Dobby`

**Comment by Ulle84** [comment]
Thanks for fixing to quickly!
